Chapter 10: implement anonymous function
The book suggests that anonymous functions should be valid as primary
expressions. I didn't implement that, as it's also how JavaScript
seems to work:

```js
function() { }
^^^^^^^^

SyntaxError: Function statements require a function name
```